### ISSUE TITLE
/etc/mysql/debian-start - wrong root password after reboot

### ISSUE THREAD

**Issue by takenek** [iredmail/iRedMail#3]
Hello
I just install fresh iRedMail 1.0 stable on Debian 10 and set MySQL root password when ask me.
After reboot server i saw information in daemon.log information about start:
/etc/mysql/debian-start
with wrong root password.

After add password to:
/etc/mysql/debian.cnf

[client]
host     = localhost
user     = root
password = "PASSWORD"
socket   = /var/run/mysqld/mysqld.sock
[mysql_upgrade]
host     = localhost
user     = root
password = "PASSWORD"
socket   = /var/run/mysqld/mysqld.sock
basedir  = /usr

everything back to normal.

Best Regards
TaKeN

**Comment by iredmail** [comment]
Could you try steps below to fix it?

- Revert your changes in `/etc/mysql/debian.cnf` (with `password=` empty).
- Login to MariaDB as root user, then update `plugin`:

```
USE mysql;
UPDATE user SET plugin='unix_socket' WHERE User='root';
```

With this change, if you're logged in as system root user, login to mysql as (mysql) root user doesn't require a password. It should fix the `/etc/mysql/debian-start` issue.

**Comment by takenek** [comment]
It`s working for me:

root@webmail:~# cat /var/log/daemon.log
Dec 23 17:45:14 webmail systemd[1]: Started MariaDB 10.3.18 database server.
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: /usr/bin/mysql_upgrade: the '--basedir' option is always ignored
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: Looking for 'mysql' as: /usr/bin/mysql
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: Looking for 'mysqlcheck' as: /usr/bin/mysqlcheck
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: Version check failed. Got the following error when calling the 'mysql' command line client
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1041]: FATAL ERROR: Upgrade failed
Dec 23 17:45:14 webmail /etc/mysql/debian-start[1087]: Checking for insecure root accounts.
Dec 23 17:45:14 webmail debian-start[1022]: ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)


root@webmail:~# mysql -u root
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 15
Server version: 10.3.18-MariaDB-0+deb10u1 Debian 10

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> USE mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [mysql]> UPDATE user SET plugin='unix_socket' WHERE User='root';
Query OK, 1 row affected (0.001 sec)
Rows matched: 1  Changed: 1  Warnings: 0

MariaDB [mysql]> quit
Bye
root@webmail:~# reboot
root@webmail:~# cat /var/log/daemon.log
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1086]: /usr/bin/mysql_upgrade: the '--basedir' option is always ignored
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1086]: Looking for 'mysql' as: /usr/bin/mysql
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1086]: Looking for 'mysqlcheck' as: /usr/bin/mysqlcheck
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1086]: This installation of MySQL is already upgraded to 10.3.18-MariaDB, use --force if you still need to run mysql_upgrade
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1170]: Checking for insecure root accounts.
Dec 23 17:46:42 webmail /etc/mysql/debian-start[1179]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables


Best Regards

**Comment by takenek** [comment]
Problem still exist in 1.1.0 - need again do:
USE mysql;
UPDATE user SET plugin='unix_socket' WHERE User='root';


Can You add this in 1.2.0?

**Comment by iredmail** [comment]
iRedMail-1.1 doesn't remove the `unix_socket` plugin:
https://github.com/iredmail/iRedMail/blob/1.1/functions/mysql.sh#L138

Maybe Debian 10 doesn't enable it by default?

**Comment by takenek** [comment]
Yes, i check and Debian 10 don`t enable this by default, so You need add in Debian 10:
USE mysql;
UPDATE user SET plugin='unix_socket' WHERE User='root';
after this working properly.

**Comment by takenek** [comment]
i just checked after boot Debian 10:
2020-04-05 15:11:20 0 [Note] /usr/sbin/mysqld: ready for connections.
Version: '10.3.22-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2020-04-05 15:11:20 0 [Note] InnoDB: Buffer pool(s) load completed at 200405 15:11:20
2020-04-05 15:11:20 8 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2020-04-05 15:11:20 9 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2020-04-05 15:11:20 10 [Warning] Access denied for user 'root'@'localhost' (using password: NO)

after update on db:
MariaDB [(none)]> USE mysql;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A
Database changed
MariaDB [mysql]> UPDATE user SET plugin='unix_socket' WHERE User='root';
Query OK, 1 row affected (0.000 sec)
Rows matched: 1  Changed: 1  Warnings: 0
MariaDB [mysql]> quit

checked log:
Version: '10.3.22-MariaDB-0+deb10u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 10
2020-04-05 15:31:30 0 [Note] InnoDB: Buffer pool(s) load completed at 200405 15:31:30
root@poczta:~#

Best Regards
