### ISSUE TITLE
ConnectionError when editing users

### ISSUE THREAD

**Issue by DavidWatkins** [iredmail/iRedMail#37]
In the admin web portal I attempt to edit users by clicking "Edit Account Profile", but the error 
```
Error: ConnectionError(ProtocolError('Connection aborted.', BadStatusLine('No status line received - the server has closed the connection',)),)
```
is printed at the top of the web page. I cannot see any error reporting happening on my Ubuntu 18.04 server. Any ideas?

**Comment by iredmail** [comment]
Please double check to make sure `mlmmjadmin` service is running. If not, try to restart it manually and try iRedAdmin-Pro again.

**Comment by DavidWatkins** [comment]
It is running, do you have another idea?

**Comment by iredmail** [comment]
Did you see any related error in log files under /var/log/? Especially “syslog” or “messages” file. 

Which Linux distribution and release are you running?

**Comment by DavidWatkins** [comment]
If I check /var/log/syslog I see the request I am making the the web server. There is no /var/log/messages file. 

```
Jun 15 02:43:25 mail iredadmin: [173.48.55.121] GET /iredadmin/profile/user/general/postmaster@livindicare.com 303 416 "https://mail.domain.com/iredadmin/users/domain.com"
Jun 15 02:43:28 mail iredadmin: [173.48.55.121] GET /iredadmin/users/domain.com?msg=ConnectionError%28ProtocolError%28%27Connection%20aborted.%27%2C%20BadStatusLine%28%27No%20status%20line%20received%20-%20the%20server%20has%20closed%20the%20connection%27%2C%29%29%2C%29 200 35087 "https://mail.domain.com/iredadmin/users/domain.com"
```

I am running Ubuntu 18.04 LTS on the Windhosts VPS.

**Comment by iredmail** [comment]
- which iRedMail release are you running?
- what are the log lines above the one you pasted above in /var/log/syslog?
- Any error in /var/log/nginx/error.log?

**Comment by DavidWatkins** [comment]
1. I am running iRedMail Pro 4.3 - the latest release. I installed it today. 
2. The full log tail is here: 
```
Jun 15 02:49:01 mail CRON[6491]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:49:01 mail CRON[6492]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:50:01 mail CRON[6517]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:50:01 mail CRON[6519]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:51:01 mail CRON[6544]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:51:01 mail CRON[6545]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:52:01 mail CRON[6570]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:52:01 mail CRON[6571]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:53:01 mail CRON[6608]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:53:01 mail CRON[6609]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:54:01 mail CRON[6634]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:54:01 mail CRON[6635]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:55:01 mail CRON[6668]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:55:01 mail CRON[6669]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:55:57 mail iredadmin: [173.48.55.121] GET /iredadmin/system/settings 200 23422 "https://mail.domain.com/iredadmin/users/domain.com?msg=ConnectionError%28ProtocolError%28%27Connection%20aborted.%27%2C%20BadStatusLine%28%27No%20status%20line%20received%20-%20the%20server%20has%20closed%20the%20connection%27%2C%29%29%2C%29"
Jun 15 02:56:01 mail CRON[6694]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:56:01 mail CRON[6695]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
Jun 15 02:56:48 mail iredadmin: [173.48.55.121] GET /iredadmin/activities/admins 200 29523 "https://mail.domain.com/iredadmin/system/settings"
Jun 15 02:57:01 mail CRON[6783]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
Jun 15 02:57:01 mail CRON[6784]: (root) CMD (/bin/bash /usr/local/bin/fail2ban_banned_db unban_db)
```
3. The log from nginx is here, however the SSL errors were from earlier when I was getting certificates from Let's Encrypt:
```
2020/06/14 22:10:44 [notice] 6564#6564: signal process started
2020/06/14 22:34:18 [error] 6565#6565: *2069 upstream timed out (110: Connection timed out) while reading response header from upstream, client: X, server: _, request: "POST /mail/?_task=mail&_action=refresh HTTP/1.1", upstream: "fastcgi://X:9999", host: "mail.domain.com", referrer: "https://mail.domain.com/mail/?_task=mail&_mbox=INBOX"
2020/06/14 23:28:04 [error] 6565#6565: *3576 open() "/opt/www/iredadmin/static/default/images/ico_attention.png" failed (2: No such file or directory), client: X, server: _, request: "GET /iredadmin/static/default/images/ico_attention.png HTTP/1.1", host: "mail.domain.com", referrer: "https://mail.domain.com/"
2020/06/14 23:28:04 [error] 6565#6565: *3646 open() "/opt/www/iredadmin/static/default/images/ico_info.png" failed (2: No such file or directory), client: X, server: _, request: "GET /iredadmin/static/default/images/ico_info.png HTTP/1.1", host: "mail.domain.com", referrer: "https://mail.domain.com/"
2020/06/15 00:45:10 [error] 6565#6565: *5239 open() "/var/www/html/Sogo" failed (2: No such file or directory), client: X, server: _, request: "GET /Sogo HTTP/1.1", host: "mail.domain.com"
2020/06/15 00:45:19 [error] 6565#6565: *5239 open() "/var/www/html/Sogo" failed (2: No such file or directory), client: X, server: _, request: "GET /Sogo HTTP/1.1", host: "mail.domain.com"
2020/06/15 01:05:54 [error] 953#953: *104 open() "/opt/www/iredadmin/static/default/images/ico_attention.png" failed (2: No such file or directory), client: X, server: _, request: "GET /iredadmin/static/default/images/ico_attention.png HTTP/1.1", host: "mail.domain.com", referrer: "https://mail.domain.com/"
2020/06/15 01:05:54 [error] 953#953: *107 open() "/opt/www/iredadmin/static/default/images/ico_info.png" failed (2: No such file or directory), client: X, server: _, request: "GET /iredadmin/static/default/images/ico_info.png HTTP/1.1", host: "mail.domain.com", referrer: "https://mail.domain.com/"
2020/06/15 01:13:20 [error] 953#953: *273 open() "/var/www/html/autodiscover/autodiscover.xml" failed (2: No such file or directory), client: X, server: _, request: "POST /autodiscover/autodiscover.xml HTTP/1.1", host: "domain.com"
2020/06/15 01:13:20 [error] 953#953: *274 open() "/var/www/html/autodiscover/autodiscover.xml" failed (2: No such file or directory), client: X, server: _, request: "POST /autodiscover/autodiscover.xml HTTP/1.1", host: "domain.com"
2020/06/15 01:47:14 [crit] 953#953: *1000 SSL_do_handshake() failed (SSL: error:14209102:SSL routines:tls_early_post_process_client_hello:unsupported protocol) while SSL handshaking, client: X, server: X:443
2020/06/15 02:23:57 [crit] 953#953: *1768 SSL_do_handshake() failed (SSL: error:1420918C:SSL routines:tls_early_post_process_client_hello:version too low) while SSL handshaking, client: X, server: X:443
```
I replaced the IP addresses with X for security reasons.

**Comment by iredmail** [comment]
- Could you restart “mlmmjadmin” AND “iredadmin” services and try again?
- Any error in /var/log/syslog AND /var/log/mlmmjadmin/mlmmjadmin.log right after the restart?

**Comment by DavidWatkins** [comment]
After restarting these are the logs:

- /var/log/syslog
```
Jun 15 03:48:27 mail uwsgi[8579]: !!! UNABLE to load uWSGI plugin: /usr/lib/uwsgi/plugins/python38_plugin.so: cannot open shared object file: No such file or directory !!!
```
- /var/log/mlmmjadmin/mlmmjadmin.log is empty

**Comment by iredmail** [comment]
> Jun 15 03:48:27 mail uwsgi[8579]: open("/usr/lib/uwsgi/plugins/python38_plugin.so"): No such file or directory [core/utils.c line 3691]
> Jun 15 03:48:27 mail uwsgi[8579]: !!! UNABLE to load uWSGI plugin: /usr/lib/uwsgi/plugins/python38_plugin.so: cannot open shared object file: No such file or directory !!!

This is the problem. Seems this server was deployed with latest development edition, not the latest stable release, iRedMail-1.2.1. And you just caught a bug of iRedMail installer. 

please make sure package “uwsgi-plugin-python3” is installed, then restart “iredadmin” service. It should fix this issue.

**Comment by DavidWatkins** [comment]
I see. I ran ```sudo apt install uwsgi-plugin-python3 --reinstall" but it looks like the issue is still there in the web console. The plugin issue is still there as well in syslog. Is there a way to install the latest stable release over my current installation?

**Comment by iredmail** [comment]
The plugin name should be “python36”, not “python38”. Please update file /opt/www/iredadmin/rc_scripts/uwsgi/debian.ini, replace “38” by “36” and restart “iredadmin” service.

**Comment by DavidWatkins** [comment]
Editing ```/opt/mlmmjadmin/rc_scripts/uwsgi/debian.ini``` with python36 instead of python38 fixed it. Thank you very much.
