### ISSUE TITLE
iRedMail-1.3.1 - FreeBSD 12.1 - fresh installation but cannot load the page of iredadmin

### ISSUE THREAD

**Issue by laiyukwa** [iredmail/iRedMail#47]
I am the user of iredadmin pro over 7 years and have been using FreeBSD over 20 years.  I have just tried to install iredmail-1.3.1 into FreeBSD 12.1 without any error or bugs.   Unfortunately, the page of iredadmin is unable to load or display in our browser but the page of Roundcube and SOGo can (only in the intranet).   The following is the error.log :-

2020/07/08 10:57:37 [error] 1450#100517: *2 writev() failed (32: Broken pipe) while sending request to upstream, client: 192.168.1.39, server: _, request: "GET /iredadmin/ HTTP/1.1", upstream: "uwsgi://127.0.0.1:7791", host: "192.168.1.229"

No error.log has been generated through internet of Real IP.   I have checked all log files but I cannot find the reason.   Please help.

**Comment by iredmail** [comment]
iRedAdmin(-Pro) is currently broken on FreeBSD, it’s mentioned in release notes of iRedMail-1.3 and it applies to iRedMail-1.3.1:
https://github.com/iredmail/iRedMail/releases/tag/1.3

**Comment by bolinches** [comment]
Hi Thanks for clarification I saw 1.3 notes but not 1.3.1 mentioned so I did the same upgrade and I was debugging now iRedAdmin-Pro issues ... I guess it is just a question of waiting. Are we talking days or week (to start a rollback instead). Thanks!

**Comment by laiyukwa** [comment]
Dear Sir,

Thank you for your assistance in this matter.   I have tried version 1.3 and 1.3.1 both of which have the same result.

In my observation,  I verily believe that it may be the problem at “uwsgi://127.0.0.1:7791 <uwsgi://127.0.0.1:7791>” which did not give the proper reply to the program.

Mr. Lai

**Comment by iredmail** [comment]
> Are we talking days or week (to start a rollback instead). Thanks!

@bolinches Few possible solutions:

1. Install another WSGI server for Python 2. e.g. `www/py-gunicorn` (install with command `make USES=python:2.7 install clean`)
2. Wait until we port iRedAdmin(-Pro) to Python 3. It will take MONTHS, i don't recommend you to wait.

**Comment by iredmail** [comment]
> In my observation, I verily believe that it may be the problem at “uwsgi://127.0.0.1:7791 <uwsgi://127.0.0.1:7791>” which did not give the proper reply to the program.

Correct. If you already upgraded uwsgi for Python 3, then you lose Python 2 support in uwsgi. But port `uwsgi` doesn't support multi versions, so we have to use another WSGI server (e.g. `www/py-gunicorn`) for Python 2 to run iRedAdmin(-Pro).

**Comment by bolinches** [comment]
> > Are we talking days or week (to start a rollback instead). Thanks!
> 
> @bolinches Few possible solutions:
> 
>     1. Install another WSGI server for Python 2. e.g. `www/py-gunicorn` (install with command `make USES=python:2.7 install clean`)
> 
>     2. Wait until we port iRedAdmin(-Pro) to Python 3. It will take MONTHS, i don't recommend you to wait.

I just moved to 3 ... before rolling back to 2 I will give a shoot to a second WSGI server. I could not find any doc about setting it I guess is just change the startup from iredmail to point to gunicorn instead. Thanks for the hint.

**Comment by iredmail** [comment]
I'm afraid that you need to read some gunicorn document to run iRedAdmin.
I'm too busy these days and didn't start working on it. Sorry about this.

**Comment by laiyukwa** [comment]
Thank you for your information and help.   I will try and also will wait for you.

On the other hand, whether or not I can install the previous version of iredmail with proper version iredadmin pro.

Mr. Lai

**Comment by iredmail** [comment]
> whether or not I can install the previous version of iredmail with proper version iredadmin pro.

No. It's same as running the latest version, because both rely on the uwsgi for Python 2, or another WSGI server for Python 2.

Currently uwsgi is installed with only Python 3 support, but on Linux platforms, uwsgi is usually packaged with plugins support and Python 2 / 3 are just 2 plugins, so on Linux we get uwsgi supporting Python 2 and 3 at the same time, but i don't know how to get uwsgi working this way on FreeBSD.

**Comment by laiyukwa** [comment]
Thank you for your information and help.

I have maintained over 10 sets FreeBSD with ZFS servers 4 sets of which are the email server using your iredmail with iredadmin-pro.   One of them is about 45G (email) per day throughput.   My configured FreeBSD is no need to install any firewall.  Since 2002 and up to now, no hacker and attack can be successfully against my FreeBSD server.   Only one occasion, a bootable disk has hardware’s failure and I need to replace the disk with a fresh installation.  Therefore, I only worry about this situation.   If any hard disk has failure at this stage, I have no workable version of iredmail which can be installed for use and replacement.    

I do not prefer to use Linux in place of Freebsd because Linux has too many versions which have their difference configure and design.

**Comment by iredmail** [comment]
I'm not encouraging you to move to Linux, just explain the situation.

Currently we just need a WSGI server for Python 2 to run iRedAdmin(-Pro). `www/py-gunicorn` is the preferred one and should be easy to get it working with iRedAdmin(-Pro).

**Comment by bolinches** [comment]
Hi

Not asking for a status update for for a rough estimation of this to be ported to python 3. Is there?

**Comment by iredmail** [comment]
- iRedAdmin-Pro is now running well on Python 3 and completely drops Python 2 support. We will soon make a new iRedAdmin open source edition based on iRedAdmin-Pro.
- There's no ETA yet, but should be done in one month.

**Comment by laiyukwa** [comment]
Dear Sir,

Thank you for your information.

Mr. Y. W. Lai

**Comment by bolinches** [comment]
Hi is iRedAdminPro working now on python3? I can only see 1.3.1 https://forum.iredmail.org/topic17065.html

**Comment by laiyukwa** [comment]
Dear Sir,

I worry the matter which has been just happened.   One of my server has been broken down due to failure of a hard disk.   I am now unable to install the new server because of your software does not allow me to install the previous version.

Please let me know what is the status of python 3 in FreeBSD ?

Mr. Lai

**Comment by iredmail** [comment]
iRedAdmin-Pro is now fully working with Python 3, we're now working on a new iRedAdmin open source edition based on the latest iRedAdmin-Pro.

**Comment by laiyukwa** [comment]
Thank you for your updated information.  Please let me know the schedule because I urgently need to install a new server.

Mr. Y. W. Lai

**Comment by iredmail** [comment]
Will try to get you a beta version this week. Stay tuned.

**Comment by bolinches** [comment]
Could you pls add the beta to the forum ... I am really waiting for this. Thanks

**Comment by laiyukwa** [comment]
Please let me know how to add the beta to the forum ?

Mr. Y. W. Lai

**Comment by laiyukwa** [comment]
Dear Sir,

Please let me know how to obtain the beta version for testing.

Mr. Lai

**Comment by iredmail** [comment]
iRedAdmin open source edition is not yet ready, stay tuned.

**Comment by iredmail** [comment]
ok, did some more cleanup, both iRedAdmin open source edition and iRedAdmin-Pro are ready for a beta release.
Tell me which linux distribution and release you prefer for testing, i will get iRedMail + iRedAdmin(-Pro) ready on that distro release first.

**Comment by laiyukwa** [comment]
Dear Sir,

My server is FreeBSD 12.1

Mr. Lai

**Comment by bartoruiz** [comment]
> ok, did some more cleanup, both iRedAdmin open source edition and iRedAdmin-Pro are ready for a beta release.
> Tell me which linux distribution and release you prefer for testing, i will get iRedMail + iRedAdmin(-Pro) ready on that distro release first.
beta should go for FreeBSD first. Linux does not have issues with uwsgi

**Comment by iredmail** [comment]
Working on FreeBSD support today, hope to get it fully working till Oct 10 (compiling packages with ports tree takes a lot time).

**Comment by iredmail** [comment]
btw, if you want to help testing, please git clone the latest iRedMail repo, then install it on a fresh/new VM or VPS.
let me know if there's any issue.

**Comment by laiyukwa** [comment]
Ok, I will try

**Comment by iredmail** [comment]
Fixed one more issue for MariaDB backend. Installation should go smoothly (for MariaDB backend) now.
Will continue testing for OpenLDAP + PostgreSQL backends. Stay tuned.

**Comment by laiyukwa** [comment]
I have used git clone to download the source of iredmail for installation to FreeBSD 12 with PostgreSQL backend.

Everything seems to be OK until Postgresql 13 Server stage was unable to build because missing /usr/ports/databases/postgresql13-server/work/stage/usr/local/share/postgresql/timezone/posixrules upon “make install” stage.

I have tried to manually install PostgreSQL server under the port tree using “make” then copying posixrules into the above location and I get the successful installation by using “make install”.  However, I continue to run iRedMail.sh script but it does not accept such installation.

Mr. Lai

**Comment by iredmail** [comment]
It's a ports tree issue, have to wait for the fix. I will try to revert to postgresql-12 for testing.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=249933
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=244403

In the meantime, could you help test MariaDB and OpenLDAP backends?

**Comment by iredmail** [comment]
- Reverted PGSQL to version 12, (PGSQL) installation is ok now.
- Also fixed a package (order) conflict.

**Comment by laiyukwa** [comment]
Dear Sir,

I successfully install the source of iredmail into my Freebsd 12.1 with Postgresql 13.   During the installation, I have noted the following matter :-

PostgreSQL 13 is only missing the file of posixrules.  Using Make to build the source is no problem.  After build, copy system file at /usr/share/zoneinfo/posixrules to the proper location and run “make install”
Pydnspython and pyrequests are manually installed from port tree
After successfully installation of iredmail,  i am unable to login into the admin page of iredadmin.  The reason is the user password in the db being missing.    I use the command to add in.   Then, no problem again.

I hope my information which can assist you.

Mr. Lai

**Comment by iredmail** [comment]
@laiyukwa Thanks for the feedback. 

- We cannot run “make” first then copy file in the installer script to handle this exception, hence we revert to pgsql-12 and all is fine. 
- py-dnspython and py-requests issue had been fixed.

Could you clone the repo and help test again? It should go smoothly without any issue.

**Comment by laiyukwa** [comment]
You must use the port tree to build “pkg” and “bash-static” because each apps under port tree will follow some setting of “pkg” to install other related program.   You can easily make postgresql13-server without any problem only missing posixrules file.

Mr. Lai

**Comment by iredmail** [comment]
> You can easily make postgresql13-server without any problem only missing posixrules file.

iRedMail installer run same “make install clean” command to install packages from ports tree, we don’t handle exception for pgsql-13 because it’s a ports tree issue.

**Comment by laiyukwa** [comment]
I know.  When the installation is broken due to the installation of postgresql13, I go to the port tree to run the command of “make” and then copy of posixrules into it.  Then, run “make install”.   I also amend your in runtime/install.status to change "export status_install_port_databases_postgresql13server='DONE'
to iRedmail.sh to continue the installation deeming the PostgreSQL being done.

Mr. Lai

**Comment by iredmail** [comment]
Please help test the latest git version with pgsql-12. No more manually handle broken pgsql-13.

**Comment by laiyukwa** [comment]
Dear Sir,

I have tried to build from the latest git version with pgsql12.  Build and installation are no problem but I try to add a domain with timezone data with the following error :-

 Error: UndefinedColumn('column "timezone" of relation "domain" does not exist\nLINE 1: ...reated, description, domain, mailboxes, maxquota, timezone) ...\n ^\n’)

Please help.

Mr. Lai

**Comment by laiyukwa** [comment]
Dear Sir,

I have found other problems as follows :-

This is an error from creating a domain 
Oct  9 17:16:19 s10 postgres[2703]: [7-1] 2020-10-09 17:16:19.008 HKT [2703] ERROR:  column "timezone" of relation "domain" does not exist at character 89
Oct  9 17:16:19 s10 postgres[2703]: [7-2] 2020-10-09 17:16:19.008 HKT [2703] STATEMENT:  INSERT INTO domain (active, aliases, created, description, domain, mailboxes, maxquota, timezone) VALUES (1, 0, '2020-10-09 09:16:19', 'Ultra System', 'ultra-storage.com', 0, 0, 'Asia/Hong_Kong')


This is an error from creating admin user
Oct  9 17:34:08 s10 iredadmin ['Traceback (most recent call last):\n', '  File "/usr/local/www/iRedAdmin-beta/libs/sqllib/admin.py", line 562, in add_admin_from_form\n    password=iredpwd.generate_password_hash(passwd),\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 473, in generate_password_hash\n    pw_hash = generate_bcrypt_password(p)\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 172, in generate_bcrypt_password\n    return "{CRYPT}" + bcrypt.hashpw(p, bcrypt.gensalt()).decode()\n', '  File "/usr/local/lib/python3.8/site-packages/bcrypt/__init__.py", line 61, in hashpw\n    raise TypeError("Unicode-objects must be encoded before hashing")\n', 'TypeError: Unicode-objects must be encoded before hashing\n'] (/usr/local/www/iRedAdmin-beta/libs/logger.py, line 38)




Mr. Lai

**Comment by iredmail** [comment]
Both should be fixed with last commits. Could you download the latest iRedAdmin-beta and upgrade for testing?
https://dl.iredmail.org/yum/misc/iRedAdmin-beta.tar.bz2

**Comment by laiyukwa** [comment]
I have just tested.  The problem of timezone is ok but I add a admin account which have the following again :-

Oct 12 11:58:03 w10 iredadmin ['Traceback (most recent call last):\n', '  File "/usr/local/www/iRedAdmin-beta/libs/sqllib/admin.py", line 562, in add_admin_from_form\n    password=iredpwd.generate_password_hash(passwd),\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 473, in generate_password_hash\n    pw_hash = generate_bcrypt_password(p)\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 172, in generate_bcrypt_password\n    return "{CRYPT}" + bcrypt.hashpw(p, bcrypt.gensalt()).decode()\n', '  File "/usr/local/lib/python3.8/site-packages/bcrypt/__init__.py", line 61, in hashpw\n    raise TypeError("Unicode-objects must be encoded before hashing")\n', 'TypeError: Unicode-objects must be encoded before hashing\n'] (/usr/local/www/iRedAdmin-beta/libs/logger.py, line 38)

 Error: TypeError('Unicode-objects must be encoded before hashing')

When I add a user into a domain, it also have the problem of “internal server error”.

Mr. Lai

**Comment by iredmail** [comment]
Will test it shortly and come back later. Thanks for the feedback. :)

**Comment by laiyukwa** [comment]
Dear Sir,

I have just git clone iredmail for rebuild and test but the error is occurred due to missing file :-

[ INFO ] + 3 of 3: https://dl.iredmail.org/yum/misc/iRedAPD-4.5.tar.gz
fetch: https://dl.iredmail.org/yum/misc/iRedAPD-4.5.tar.gz: Not Found
[ INFO ] Validate downloaded source tarballs ...
sha256: misc/iRedAPD-4.5.tar.gz: No such file or directory
2a3



Mr. Lai

**Comment by iredmail** [comment]
Fixed: https://dl.iredmail.org/yum/misc/iRedAPD-4.5.tar.gz

btw, you can download it from github too:
https://github.com/iredmail/iRedAPD/tags

**Comment by laiyukwa** [comment]
Dear Sirs,

I have just finished the test but it still has the following problem during creating the user :-

Oct 12 17:16:46 s10 iredadmin ['Traceback (most recent call last):\n', '  File "/usr/local/www/iRedAdmin-beta/libs/sqllib/admin.py", line 562, in add_admin_from_form\n    password=iredpwd.generate_password_hash(passwd),\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 473, in generate_password_hash\n    pw_hash = generate_bcrypt_password(p)\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 172, in generate_bcrypt_password\n    return "{CRYPT}" + bcrypt.hashpw(p, bcrypt.gensalt()).decode()\n', '  File "/usr/local/lib/python3.8/site-packages/bcrypt/__init__.py", line 61, in hashpw\n    raise TypeError("Unicode-objects must be encoded before hashing")\n', 'TypeError: Unicode-objects must be encoded before hashing\n'] (/usr/local/www/iRedAdmin-beta/libs/logger.py, line 38)


Mr. Lai

**Comment by iredmail** [comment]
It was fixed 3 hours ago. You can download the latest git version and upgrade. 
https://github.com/iredmail/iRedAdmin/commits/master

Thank you very much for the feedback and help testing.

**Comment by laiyukwa** [comment]
Dear Sirs,

In my understanding, the existing problem is only affecting the script in the path of iredadmin.  If it is true, it is no need to rebuild all the programs and library.   Only to modify three files of admin.py, iredpwd.py and profile.html. 

I have followed your modification to amend these 3 files but the error is still appeared as follows :-

 Error: TypeError('Unicode-objects must be encoded before hashing')
 
If my understand is being wrong,  please tell me

Mr. Lai

**Comment by iredmail** [comment]
After modified files, please restart “iredadmin” service to load modified files and try again.

**Comment by doug-one** [comment]
Is freebsd supported under the latest release? Can I just clone the repo and run the same Script?

Thanks

**Comment by iredmail** [comment]
The latest git edition should work on FreeBSD, but the iRedAdmin OSE edition still has few small bugs. It's ok for testing, but don't run it on production server please.

**Comment by laiyukwa** [comment]
I have just downloaded from the latest git edition and carried out a test.  However, the following errors are appeared during the creation of admin user and user of a domain :-

 Error: TypeError('Unicode-objects must be encoded before hashing’)

Oct 14 14:16:35 d10 iredadmin ['Traceback (most recent call last):\n', '  File "/usr/local/www/iRedAdmin-beta/libs/sqllib/admin.py", line 562, in add_admin_from_form\n    password=iredpwd.generate_password_hash(passwd),\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 473, in generate_password_hash\n    pw_hash = generate_bcrypt_password(p)\n', '  File "/usr/local/www/iRedAdmin-beta/libs/iredpwd.py", line 172, in generate_bcrypt_password\n    return "{CRYPT}" + bcrypt.hashpw(p, bcrypt.gensalt()).decode()\n', '  File "/usr/local/lib/python3.8/site-packages/bcrypt/__init__.py", line 61, in hashpw\n    raise TypeError("Unicode-objects must be encoded before hashing")\n', 'TypeError: Unicode-objects must be encoded before hashing\n'] (/usr/local/www/iRedAdmin-beta/libs/logger.py, line 38)

Mr. Lai

**Comment by iredmail** [comment]
- Did you try the latest git version of iRedAdmin or iRedMail? This should be fixed in latest git version of iRedAdmin, but it's not repacked and shipped in iRedMail yet. I will fix this. As a temporary fix, you can download the latest git version of iRedAdmin and upgrade manually.
- Is it PGSQL backend?

**Comment by iredmail** [comment]
Updated re-packed iRedAdmin-beta. I'm testing locally.

**Comment by laiyukwa** [comment]
I downloaded from git  of iRedMail today morning which I verily believe it is latest version.

If the git version of iRedAdmin is difference from iRedMail,  please tell me whether or not I use upgrade script from the tools to upgrade this being correct ?

**Comment by iredmail** [comment]
@laiyukwa Please download git version of iRedAdmin and upgrade manually:

- git repo: https://github.com/iredmail/iredadmin
- upgrade tutorial: https://docs.iredmail.org/migrate.or.upgrade.iredadmin.html

**Comment by laiyukwa** [comment]
Error message is :-

root@d10:~/iredadmin/tools # bash upgrade_iredadmin.sh
* Detected Linux/BSD distribution: FREEBSD
* HTTP server root: /usr/local/www
* Found iRedAdmin directory: /usr/local/www/iredadmin, symbol link of iRedAdmin-org
* Found iRedAdmin config file: /usr/local/www/iredadmin/settings.py
<<< ERROR >>> Cannot find new version of iRedAdmin in current directory. Exit.

**Comment by iredmail** [comment]
Please rename the extracted iRedAdmin directory to something like `iRedAdmin-beta`, then run the upgrade script.

**Comment by laiyukwa** [comment]
Sorry,  the same error

root@d10:~/iredadmin-beta/tools # bash upgrade_iredadmin.sh
* Detected Linux/BSD distribution: FREEBSD
* HTTP server root: /usr/local/www
* Found iRedAdmin directory: /usr/local/www/iredadmin, symbol link of iRedAdmin-beta
* Found iRedAdmin config file: /usr/local/www/iredadmin/settings.py
<<< ERROR >>> Cannot find new version of iRedAdmin in current directory. Exit.

**Comment by iredmail** [comment]
It's case sensitive, `iRedAdmin-beta`, not `iredadmin-beta`.

**Comment by laiyukwa** [comment]
Thank you for your assistance.   Mainly the problem is resolved for creating admin user only.   When I create an usual user of a domain without giving the size of mailbox, I obtain an error as follows :-

 Error: InvalidTextRepresentation('invalid input syntax for type bigint: ""\nLINE 1: ...5OCCEVwcK7wuvYr54NuiPSpS\', \'2020-10-14 08:27:27\', \'\', \'/var/...\n ^\n’)

Oct 14 16:27:27 d10 postgres[1474]: [7-1] 2020-10-14 16:27:27.856 HKT [1474] ERROR:  invalid input syntax for type bigint: "" at character 433
Oct 14 16:27:27 d10 postgres[1474]: [7-2] 2020-10-14 16:27:27.856 HKT [1474] STATEMENT:  INSERT INTO mailbox (active, created, domain, language, mailboxfolder, mailboxformat, maildir, name, password, passwordlastchange, quota, storagebasedirectory, storagenode, username) VALUES (1, '2020-10-14 08:27:27', 'ultra-storage.com', 'en_US', 'Maildir', 'maildir', 'ultra-storage.com/l/a/i/laiyukwa-2020.10.14.16.27.27/', 'laiyukwa', '{CRYPT}$2b$12$UwxQP0ROa.BQ5zfRRwg9vuDZuhQbJ5OCCEVwcK7wuvYr54NuiPSpS', '2020-10-14 08:27:27', '', '/var/vmail', 'vmail1', 'laiyukwa@ultra-storage.com')

If I give the size of mailbox, it appear being ok

**Comment by iredmail** [comment]
@laiyukwa Issue has been fixed in latest iRedAdmin-beta. You can upgrade it for testing:
https://dl.iredmail.org/yum/misc/iRedAdmin-beta.tar.bz2

**Comment by laiyukwa** [comment]
This version is seemed to be ok.

**Comment by bolinches** [comment]
I added this last version and on MySWL backed went OK (It is not the Pro version so I do not have any of the Pro stuff) but instlal went OK and I can log in

**Comment by laiyukwa** [comment]
The existing Pro version does not work on this version.   When the new Pro version will be released ?

**Comment by iredmail** [comment]
> The existing Pro version does not work on this version. When the new Pro version will be released ?

Same day as the new iRedMail release.
If you need iRedAdmin-Pro now, i can send you a beta version with Python 3 support. :)

This issue should be closed now since it's solved. Feel free to open new issue if there's any problem.

**Comment by laiyukwa** [comment]
Please let me have the beta version of iRedAdmin-Pro with Python3 support for testing.

**Comment by iredmail** [comment]
hi @laiyukwa 

Please contact us with your iRedAdmin-Pro license key or owner's email address: https://www.iredmail.org/contact.html

**Comment by laiyukwa** [comment]
I am holder of live license of iRedAdmin-Pro the key of which is 76B039D4-D79C-423A-BE2E-9D233D6FFDA2 

Please let me have the beta version of iRedAdmin-Pro for my test.

Mr. Lai

**Comment by iredmail** [comment]
DO NOT LEAK YOUR iRedAdmin-Pro LICENSE KEY. That's why i asked you to contact us by email...

**Comment by laiyukwa** [comment]
noted

**Comment by laiyukwa** [comment]
Dear Sirs,

I have tried to install iredmail-1.3.2 on FreeBSD 12.2.   Everything seems to be ok but I am unable to login iredadmin page due to incorrect password.   I check everything being nothing wrong but I found that the password stored in PostgreSQL is using BCRYPT instead of SSHA or SSHA512.

Please help.

Mr. Lai

**Comment by iredmail** [comment]
- BCRYPT is correct.
- Could you reset `postmaster@`'s password and try login again? Does it work?

**Comment by laiyukwa** [comment]
I have reset the password using   -  doveadm pw -s ’SSH512’  and then update mailbox .

I only login the webmail but cannot login iredadmin page.

On the other hand, "doveadm pw -s” cannot support ‘BCRYPT’


Mr. Lai

**Comment by iredmail** [comment]
Use the script `/usr/local/www/iredadmin/tools/reset_user_password.py` to reset password, then try to login to webmail and iRedAdmin.

**Comment by laiyukwa** [comment]
The Result is 

reset_user_password.py: line 8: syntax error near unexpected token `('
reset_user_password.py: line 8: `def usage():’

**Comment by iredmail** [comment]
Try:

```
cd /usr/local/www/iredadmin/tools/
python3 reset_user_password.py <email> <plain-password>
```

**Comment by laiyukwa** [comment]
The result is same being unable to login.

I check the database record being changed to {CYRPT}.     But after the fresh installation, the type is {BCYRPT}

Mr. Lai

**Comment by iredmail** [comment]
I will check later, seems a bug of iRedAdmin. Could you help create a new issue here and leave this one closed?
